### PR TITLE
Twitter now requires the use of HTTPS for streaming connections

### PR DESCRIPTION
**Pull request by deedubs**

### CODE REVIEW

**Comment by deedubs** [comment]
bump

**Comment by deserat** [comment]
seriously this hasn't been fixed yet? assuming this library has been abandoned.

**Comment by axkibe** [comment]
Yes I also suppose its abandoned and thus looking for a new maintainer. If I'd had a little more time and not already half a dozend proejcts I'd do it. I got quite some modifications to this library for myself already (cookies instead of cookie, keygrip proper callbacks from get, etc.. But this is always just changed to my needs, instead of properly refactoring the code for general use.

**Comment by jdub** [comment]
Thanks for your pull request, I'm sorry I haven't been maintaining node-twitter. I have just merged an equivalent change.

**Pull request closed without merging**
